num1 =int(input("enter the first number: "))
num2 =int(input("enter the number 2: "))

print("=====")
print(type(num1))
print("========")
print(type(num2))
print("===========")
print("the sum is ", num1+num2)
print("===========")
input("Press enter to exit")